### ISSUE TITLE
Bug：生成messID重复

### ISSUE THREAD

**Issue by meikongwuzui** [yunba/yunba-csharp-sdk#1]
private ulong MessageID
        {
            get
            {
                ulong ms = (ulong)Math.Round((DateTime.Now - EPOCH).TotalMilliseconds);
                ms = ms << 23;

```
            Random rnd = new Random();
            ulong id = ms | (uint)(rnd.Next() & 0x7FFFFF);
            return id;
        }
    }
```

**Comment by wuyingfengsui** [comment]
https://github.com/yunba/yunba-csharp-sdk/commit/b19d64693b8bf1ca834ea8d7b5e0b1075b5ef873
